一点建议性修改
SangKa/PWA-Book-CN pull request #23
Opened 2018-01-04 09:11 UTC by zwwill

2018-01-06 00:14 UTC, SangKa requested changes
感谢 PR

2018-01-06 00:14 UTC, SangKa commented on ch02/2.1.md
> +第1章中 Alex Russell 的引言 (关于汲取了所需要的所有原生功能的网站) 完美地总结了 PWA 的特性，而且我首次开始尝试 Service Workers 时也是这种感觉。当我真正理解了它们工作的基本概念后，我慢慢地意识，到它们的强大其实远远超乎我的想象，甚至让我脑洞大开。随着我越来越深入地了解 PWA，并开始尝试每次学习使用一个新功能或“元素”。通常学习新技术就像是在爬山，如果你以
`我慢慢地意识，到它们的强大其实远远超乎我的想象`
这里的断句会导致不通顺

2018-01-06 00:14 UTC, SangKa commented on ch02/2.1.md
> +第1章中 Alex Russell 的引言 (关于汲取了所需要的所有原生功能的网站) 完美地总结了 PWA 的特性，而且我首次开始尝试 Service Workers 时也是这种感觉。当我真正理解了它们工作的基本概念后，我慢慢地意识，到它们的强大其实远远超乎我的想象，甚至让我脑洞大开。随着我越来越深入地了解 PWA，并开始尝试每次学习使用一个新功能或“元素”。通常学习新技术就像是在爬山，如果你以
`随着我越来越深入地了解 PWA`
原文中的是 more 并非 deeper

2018-01-06 00:14 UTC, SangKa commented on ch02/2.1.md
> +第1章中 Alex Russell 的引言 (关于汲取了所需要的所有原生功能的网站) 完美地总结了 PWA 的特性，而且我首次开始尝试 Service Workers 时也是这种感觉。当我真正理解了它们工作的基本概念后，我慢慢地意识，到它们的强大其实远远超乎我的想象，甚至让我脑洞大开。随着我越来越深入地了解 PWA，并开始尝试每次学习使用一个新功能或“元素”。通常学习新技术就像是在爬山，如果你以
`你将很快掌握 PWA 这门艺术`
PWA 的艺术和 PWA 这门艺术还是有区别的

2018-01-06 00:14 UTC, SangKa commented on ch02/2.1.md
> +我相信，很多读这本书的人都会在他们目前的项目中花费大量的时间和精力。幸运的是，构建一个 PWA 并不需要你从头开始把项目再重做一遍。当我尝试改善现有的应用时，每当我觉得一个功能对用户有益并能为他们提供增强的体验时，我就会添加这个新“功能”。我喜欢把每个 PWA 的新功能都看作是可以升级超级马里奥的新蘑菇！
`我喜欢把每个 PWA 的新功能都看作是可以升级超级马里奥的新蘑菇！`
这里指代的是升级 而不是🍄

2018-01-06 00:14 UTC, SangKa commented on ch02/2.1.md
> +如果你认为你现成的 Web 应用可以从 PWA 的功能中受益，我推荐你一个叫做 Lighthouse ([https://github.com/GoogleChrome/lighthouse](https://github.com/GoogleChrome/lighthouse)) 的便利工具。它提供 Web 应用相关的有用的性能信息和审核信息。(参见图2.1)
`现成的` -> `现有的` 更通顺

2018-01-06 00:14 UTC, SangKa commented on ch02/2.1.md
> +此刻，你可能想知道，有哪些功能是你可能想要添加到现有网站上的！ Service Workers 开辟了一个充满可能性的世界，所以，决定从哪里入手是至关重要的。在本书的其余部分，每章都会重点介绍 PWA 的一个新功能，无论你是为了优化现有网站，还是为了构建一个全新的网站，都可以即学即用。
`你可能想知道，有哪些功能是你可能想要添加到现有网站上的！`
感觉这里不适合断句

2018-01-06 06:43 UTC, zwwill reviewed
你再看一下我的更正评论，你确认后我会重新提一个PR

2018-01-06 06:43 UTC, zwwill commented on ch02/2.1.md
> +我相信，很多读这本书的人都会在他们目前的项目中花费大量的时间和精力。幸运的是，构建一个 PWA 并不需要你从头开始把项目再重做一遍。当我尝试改善现有的应用时，每当我觉得一个功能对用户有益并能为他们提供增强的体验时，我就会添加这个新“功能”。我喜欢把每个 PWA 的新功能都看作是可以升级超级马里奥的新蘑菇！
我认为：PWA 是对现有 web app 的一种优化升级，升级的效果是由引入了 PWA 带来的，类同于吃了蘑菇的马里奥

2018-01-06 06:43 UTC, zwwill commented on ch02/2.1.md
> +第1章中 Alex Russell 的引言 (关于汲取了所需要的所有原生功能的网站) 完美地总结了 PWA 的特性，而且我首次开始尝试 Service Workers 时也是这种感觉。当我真正理解了它们工作的基本概念后，我慢慢地意识，到它们的强大其实远远超乎我的想象，甚至让我脑洞大开。随着我越来越深入地了解 PWA，并开始尝试每次学习使用一个新功能或“元素”。通常学习新技术就像是在爬山，如果你以
第一个断句手误，【我慢慢地意识到，它们的强大其实远远超乎我的想象】
第二个我同意，上下文也是 more
第三个没有原文，具体的我遵循你的意见，使用【PWA的艺术】

2018-01-06 06:43 UTC, zwwill commented on ch02/2.1.md
> +如果你认为你现成的 Web 应用可以从 PWA 的功能中受益，我推荐你一个叫做 Lighthouse ([https://github.com/GoogleChrome/lighthouse](https://github.com/GoogleChrome/lighthouse)) 的便利工具。它提供 Web 应用相关的有用的性能信息和审核信息。(参见图2.1)
同意

2018-01-06 06:43 UTC, zwwill commented on ch02/2.1.md
> +此刻，你可能想知道，有哪些功能是你可能想要添加到现有网站上的！ Service Workers 开辟了一个充满可能性的世界，所以，决定从哪里入手是至关重要的。在本书的其余部分，每章都会重点介绍 PWA 的一个新功能，无论你是为了优化现有网站，还是为了构建一个全新的网站，都可以即学即用。
你看看这样行不行【此刻，你可能想了解有哪些功能是可以添加到你现有网站上的！】

2018-01-07 09:07 UTC, SangKa commented on ch02/2.1.md
> +第1章中 Alex Russell 的引言 (关于汲取了所需要的所有原生功能的网站) 完美地总结了 PWA 的特性，而且我首次开始尝试 Service Workers 时也是这种感觉。当我真正理解了它们工作的基本概念后，我慢慢地意识，到它们的强大其实远远超乎我的想象，甚至让我脑洞大开。随着我越来越深入地了解 PWA，并开始尝试每次学习使用一个新功能或“元素”。通常学习新技术就像是在爬山，如果你以
同意

2018-01-07 09:08 UTC, SangKa commented on ch02/2.1.md
> +我相信，很多读这本书的人都会在他们目前的项目中花费大量的时间和精力。幸运的是，构建一个 PWA 并不需要你从头开始把项目再重做一遍。当我尝试改善现有的应用时，每当我觉得一个功能对用户有益并能为他们提供增强的体验时，我就会添加这个新“功能”。我喜欢把每个 PWA 的新功能都看作是可以升级超级马里奥的新蘑菇！
同意 之前理解的太字面化 每个功能都是升级吃的蘑菇

2018-01-07 09:09 UTC, SangKa commented on ch02/2.1.md
> +此刻，你可能想知道，有哪些功能是你可能想要添加到现有网站上的！ Service Workers 开辟了一个充满可能性的世界，所以，决定从哪里入手是至关重要的。在本书的其余部分，每章都会重点介绍 PWA 的一个新功能，无论你是为了优化现有网站，还是为了构建一个全新的网站，都可以即学即用。
可以

2018-01-07 09:10 UTC, SangKa commented
@zwwill 已确认 可以更新下 我好合并

2018-01-07 10:30 UTC, zwwill commented
@SangKa 已更新

2018-01-07 10:39 UTC, SangKa approved these changes

2018-01-07 10:39 UTC, merged